### ISSUE TITLE
missing images listed in `carbide-images.txt`

### ISSUE THREAD

**Issue by zackbradys** [rancherfederal/carbide-releases#1]
In the Carbide Release Assets, specifically the `carbide-images.txt` file, a list of images are published. Currently the two existing releases are missing a few images. Please see below:

https://github.com/rancherfederal/carbide-releases/releases

**For Carbide Release `v0.1.0`:**
* `rgcrprod.azurecr.us/carbide/carbide-whitelabel:0.1.0`

**For Carbide Release `v0.1.1`:**
* `rgcrprod.azurecr.us/carbide/carbide-whitelabel:0.1.1` (currently has `0.1.0`)
* `rgcrprod.azurecr.us/carbide/heimdall-proxy:0.1.1`
* `rgcrprod.azurecr.us/carbide/heimdall2:0.1.1`
* `rgcrprod.azurecr.us/carbide/postgres:13`

**Comment by amartin120** [comment]
This has gotten a bit out of sync while we work to redefine how we roll out official "carbide-releases".  As a monkey patch of sorts, both the `0.1.0` and `0.1.1` release has an updated list of images.  We totally understand that sounds a bit off but we're actively working to iron this process out going forward.
