### ISSUE TITLE
STIGATRON profiles for k8s 1.27, 1.28

### ISSUE THREAD

**Issue by jtrewartha** [rancherfederal/carbide-releases#4]
Currently STIGATRON only has profiles up to K8s 1.26 which is no longer the up to date supported version by Rancher. 

Are there STIGATRON profiles available for 1.27 and 1.28 releases or is there an ETA on when these should be expected?

**Comment by bgulla** [comment]
Yes- these will be updated shortly.

Brandon

**Comment by zackbradys** [comment]
closing as complete... `stigatron` has profiles for up to `v1.29`
