### ISSUE TITLE
[RFE] Request for Carbide Images in archive format

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/carbide-releases#5]
The customer is requesting Carbide images in a tarball format. Having Carbide images in this format is essential for their project.

**Comment by HoustonDad** [comment]
At this time, RGS provides archives for customers to download K3S, Rancher and RKE2 without having to use docker pull for the images.

https://rfed-public-images.s3-us-gov-west-1.amazonaws.com/

Customers are requesting the same thing, but with Carbide images. We have three customers with this request now

**Comment by zackbradys** [comment]
closing as complete per https://portal.ranchercarbide.dev
