### ISSUE TITLE
[RFE] CARBIDE: Remove all unnecessary node/cluster drivers and languages

### ISSUE THREAD

**Issue by jrodonnell** [rancherfederal/carbide-releases#6]
The only node and cluster drivers that should be visible in the UI are the ones that are installed or enabled by default, all others should be removed. This should be doable by removing the relevant `nodeDriver` and `kontainerDriver` objects from the Helm templates.

There's also an option in the user's Preferences menu to select other languages, these should be removed as well. This may be a bit trickier as I believe the values in the dropdown are baked into the JavaScript but still should be removed somehow.

**Comment by dweomer** [comment]
- removed chinese language (zh) support:
  - https://github.com/rancher-government-carbide/rancher-dashboard-private/commit/d6034aba243cb6c791173b09fc00ef94315e9ec1 ➡ [rancher/dashboard@carbide/2.9/fork/30/remove-zh-l10n](https://github.com/rancher-government-carbide/rancher-dashboard-private/tree/carbide/2.9/fork/30/remove-zh-l10n)
- removed chinese infra providers:
  - https://github.com/rancher-government-carbide/rancher-manager-private/commit/2f7d1140f1fe8f8f821909eaae3d33197f101d3a ➡ [rancher/rancher@carbide/2.9/fork/20/remove-chinese-providers](https://github.com/rancher-government-carbide/rancher-manager-private/tree/carbide/2.9/fork/20/remove-chinese-providers)

**Comment by dweomer** [comment]
- https://github.com/rancher-government-carbide/rancher-manager-private/tree/carbide/2.9/patch/4
